version: "3.4"

services:
  suggest:
    build:
      context: .
      dockerfile: .docker/suggest_service/Dockerfile
    environment:
     - LOGLEVEL=error
     - ELASTIC_URI=http://localhost:9200
     - ELASTIC_INDEX=artikelbank_dev
     - MONGO_URI=mongodb://127.0.0.1:27017
     - MONGO_DB=artikelbank_dev
    dns:
        - 8.8.8.8
        - 8.8.4.4
    network_mode: "host"